from typing import Any, ClassVar, Union


class FrozenDict(dict):
    _block_msg: ClassVar[str] = ...
    def __delitem__(self, key: Any) -> None: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def clear(self) -> None: ...
    def pop(self, key: Any, default: Any = ...) -> None: ...
    def popitem(self) -> tuple[Any, Any]: ...
    def setdefault(self, key: Any, default: Any = ...) -> None: ...
    def update(self, *E: Any, **F: Any) -> None: ...
    @staticmethod
    def _freeze_arg(in_arg: Any) -> Any: ...
    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...  # type: ignore


AttributeDict = dict[str, Any]
EdgeEndpoint = Union[str, bytes, int, float, FrozenDict]
