# SPDX-FileCopyrightText: 2026 pydot contributors
#
# SPDX-License-Identifier: MIT

from __future__ import annotations

import pydot.classes
import re
import subprocess
from pydot.classes import AttributeDict, FrozenDict, EdgeEndpoint
from typing import Any, ClassVar, Sequence, Union

GRAPH_ATTRIBUTES: set[str]
EDGE_ATTRIBUTES: set[str]
NODE_ATTRIBUTES: set[str]
CLUSTER_ATTRIBUTES: set[str]
OUTPUT_FORMATS: set[str]
DEFAULT_PROGRAMS: set[str]
dot_keywords: list[str]

EdgeDefinition = Union[EdgeEndpoint, Node, Subgraph, Cluster]

re_dbl_quoted: re.Pattern
re_numeric: re.Pattern
re_html: re.Pattern
id_re_with_port: re.Pattern
id_re_alpha_nums: re.Pattern
id_re_alpha_nums_with_ports: re.Pattern

class frozendict(pydot.classes.FrozenDict):
    """Deprecated alias for pydot.classes.FrozenDict."""
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
def is_windows() -> bool: ...
def is_anaconda() -> bool: ...
def get_executable_extension() -> str: ...
def call_graphviz(program: str, arguments: list[str], working_dir: str | bytes, **kwargs: Any) -> tuple[bytes, bytes, subprocess.Popen[bytes]]: ...
def make_quoted(s: str) -> str:
    """Transform a string into a quoted string, escaping specials."""
def any_needs_quotes(s: str) -> bool | None:
    """Determine if a string needs to be quoted.

    Returns True, False, or None if the result is indeterminate.
    """
def id_needs_quotes(s: str) -> bool:
    """Checks whether a string is a dot language ID.

    It will check whether the string is solely composed
    by the characters allowed in an ID or not.
    If the string is one of the reserved keywords it will
    need quotes too but the user will need to add them
    manually.
    """
def quote_id_if_necessary(s: str, unquoted_keywords: Sequence[str] | None = ...) -> str:
    """Enclose identifier in quotes, if needed."""
def quote_attr_if_necessary(s: str) -> str:
    """Enclose attribute value in quotes, if needed."""
def graph_from_dot_data(s: str) -> list[pydot.Dot] | None:
    """Load graphs from DOT description in string `s`.

    This function is NOT thread-safe due to the internal use of `pyparsing`.
    Use a lock if needed.

    @param s: string in [DOT language](
        https://en.wikipedia.org/wiki/DOT_(graph_description_language))

    @return: Graphs that result from parsing.
    @rtype: `list` of `pydot.Dot`
    """
def graph_from_dot_file(path: str | bytes, encoding: str | None = ...) -> list[pydot.Dot] | None:
    """Load graphs from DOT file at `path`.

    This function is NOT thread-safe due to the internal use of `pyparsing`.
    Use a lock if needed.

    @param path: to DOT file
    @param encoding: as passed to `io.open`.
        For example, `'utf-8'`.

    @return: Graphs that result from parsing.
    @rtype: `list` of `pydot.Dot`
    """
def graph_from_edges(edge_list: Sequence[Any], node_prefix: str = ..., directed: bool = ...) -> Dot:
    """Creates a basic graph out of an edge list.

    The edge list has to be a list of tuples representing
    the nodes connected by the edge.
    The values can be anything: bool, int, float, str.

    If the graph is undirected by default, it is only
    calculated from one of the symmetric halves of the matrix.
    """
def graph_from_adjacency_matrix(matrix: Sequence[Sequence[Any]], node_prefix: str = ..., directed: bool = ...) -> Dot:
    """Creates a basic graph out of an adjacency matrix.

    The matrix has to be a list of rows of values
    representing an adjacency matrix.
    The values can be anything: bool, int, float, as long
    as they can evaluate to True or False.
    """
def graph_from_incidence_matrix(matrix: Sequence[Sequence[Any]], node_prefix: str = ..., directed: bool = ...) -> Dot:
    """Creates a basic graph out of an incidence matrix.

    The matrix has to be a list of rows of values
    representing an incidence matrix.
    The values can be anything: bool, int, float, as long
    as they can evaluate to True or False.
    """

class Common:
    """Common information to several classes.

    Should not be directly used, several classes are derived from
    this one.
    """
    obj_dict: ClassVar[dict] = ...
    def __init__(self, obj_dict: AttributeDict | None = ...) -> None: ...
    def set_parent_graph(self, parent_graph: Common | None) -> None: ...
    def get_parent_graph(self) -> Graph | None: ...
    def get_top_graph_type(self, default: str = ...) -> str:
        """Find the topmost parent graph type for the current object."""
    def set(self, name: str, value: Any) -> None:
        """Set an attribute value by name.

        Given an attribute 'name' it will set its value to 'value'.
        There's always the possibility of using the methods:

            set_'name'(value)

        which are defined for standard graphviz attributes.
        """
    def get(self, name: str) -> Any:
        """Get an attribute value by name.

        Given an attribute 'name' it will get its value.
        There's always the possibility of using the methods:

            get_'name'()

        which are defined for standard graphviz attributes.
        """
    def get_attributes(self) -> AttributeDict:
        """Get attributes of the object"""
    def set_sequence(self, seq: int) -> None:
        """Set sequence"""
    def get_sequence(self) -> int | None:
        """Get sequence"""
    @staticmethod
    def get_indent(indent: Any, indent_level: int) -> str: ...
    def formatted_attr_list(self) -> list[str]:
        """Return a list of the class's attributes as formatted strings."""
    def attrs_string(self, prefix: str = ...) -> str:
        """Format the current attributes list for output.

        The `prefix` string will be prepended if and only if some
        output is generated."""

class Node(Common):
    """A graph node.

    This class represents a graph's node with all its attributes.

    node(name, attribute=value, ...)

    name: node's name

    All the attributes defined in the Graphviz dot language should
    be supported.
    """
    def __init__(self, name: str = ..., obj_dict: AttributeDict | None = ..., **attrs: Any) -> None: ...
    def set_name(self, node_name: str | None) -> None:
        """Set the node's name."""
    def get_name(self) -> str:
        """Get the node's name."""
    def get_port(self) -> str | None:
        """Get the node's port."""
    def add_style(self, style: str) -> None: ...
    def to_string(self, indent: Any = ..., indent_level: int = ...) -> str:
        """Return string representation of node in DOT language."""
    def get_pos(self) -> Any: ...
    def set_pos(self, value: Any) -> None: ...
    def get_distortion(self) -> Any: ...
    def set_distortion(self, value: Any) -> None: ...
    def get_penwidth(self) -> Any: ...
    def set_penwidth(self, value: Any) -> None: ...
    def get_label(self) -> Any: ...
    def set_label(self, value: Any) -> None: ...
    def get_height(self) -> Any: ...
    def set_height(self, value: Any) -> None: ...
    def get_group(self) -> Any: ...
    def set_group(self, value: Any) -> None: ...
    def get_id(self) -> Any: ...
    def set_id(self, value: Any) -> None: ...
    def get_imagescale(self) -> Any: ...
    def set_imagescale(self, value: Any) -> None: ...
    def get_margin(self) -> Any: ...
    def set_margin(self, value: Any) -> None: ...
    def get_fontsize(self) -> Any: ...
    def set_fontsize(self, value: Any) -> None: ...
    def get_layer(self) -> Any: ...
    def set_layer(self, value: Any) -> None: ...
    def get_colorscheme(self) -> Any: ...
    def set_colorscheme(self, value: Any) -> None: ...
    def get_image(self) -> Any: ...
    def set_image(self, value: Any) -> None: ...
    def get_comment(self) -> Any: ...
    def set_comment(self, value: Any) -> None: ...
    def get_color(self) -> Any: ...
    def set_color(self, value: Any) -> None: ...
    def get_rects(self) -> Any: ...
    def set_rects(self, value: Any) -> None: ...
    def get_regular(self) -> Any: ...
    def set_regular(self, value: Any) -> None: ...
    def get_pin(self) -> Any: ...
    def set_pin(self, value: Any) -> None: ...
    def get_target(self) -> Any: ...
    def set_target(self, value: Any) -> None: ...
    def get_z(self) -> Any: ...
    def set_z(self, value: Any) -> None: ...
    def get_shape(self) -> Any: ...
    def set_shape(self, value: Any) -> None: ...
    def get_fillcolor(self) -> Any: ...
    def set_fillcolor(self, value: Any) -> None: ...
    def get_orientation(self) -> Any: ...
    def set_orientation(self, value: Any) -> None: ...
    def get_style(self) -> Any: ...
    def set_style(self, value: Any) -> None: ...
    def get_fontname(self) -> Any: ...
    def set_fontname(self, value: Any) -> None: ...
    def get_texmode(self) -> Any: ...
    def set_texmode(self, value: Any) -> None: ...
    def get_shapefile(self) -> Any: ...
    def set_shapefile(self, value: Any) -> None: ...
    def get_labelloc(self) -> Any: ...
    def set_labelloc(self, value: Any) -> None: ...
    def get_sides(self) -> Any: ...
    def set_sides(self, value: Any) -> None: ...
    def get_nojustify(self) -> Any: ...
    def set_nojustify(self, value: Any) -> None: ...
    def get_showboxes(self) -> Any: ...
    def set_showboxes(self, value: Any) -> None: ...
    def get_tooltip(self) -> Any: ...
    def set_tooltip(self, value: Any) -> None: ...
    def get_fixedsize(self) -> Any: ...
    def set_fixedsize(self, value: Any) -> None: ...
    def get_width(self) -> Any: ...
    def set_width(self, value: Any) -> None: ...
    def get_samplepoints(self) -> Any: ...
    def set_samplepoints(self, value: Any) -> None: ...
    def get_sortv(self) -> Any: ...
    def set_sortv(self, value: Any) -> None: ...
    def get_texlbl(self) -> Any: ...
    def set_texlbl(self, value: Any) -> None: ...
    def get_skew(self) -> Any: ...
    def set_skew(self, value: Any) -> None: ...
    def get_URL(self) -> Any: ...
    def set_URL(self, value: Any) -> None: ...
    def get_fontcolor(self) -> Any: ...
    def set_fontcolor(self, value: Any) -> None: ...
    def get_vertices(self) -> Any: ...
    def set_vertices(self, value: Any) -> None: ...
    def get_peripheries(self) -> Any: ...
    def set_peripheries(self, value: Any) -> None: ...
    def get_root(self) -> Any: ...
    def set_root(self, value: Any) -> None: ...

class Edge(Common):
    """A graph edge.

    This class represents a graph's edge with all its attributes.

    edge(src, dst, attribute=value, ...)

    src: source node, subgraph or cluster
    dst: destination node, subgraph or cluster

    `src` and `dst` can be specified as a `Node`, `Subgraph` or
    `Cluster` object, or as the name string of such a component.

    All the attributes defined in the Graphviz dot language should
    be supported.

    Attributes can be set through the dynamically generated methods:

     set_[attribute name], i.e. set_label, set_fontname

    or directly by using the instance's special dictionary:

     Edge.obj_dict['attributes'][attribute name], i.e.

        edge_instance.obj_dict['attributes']['label']
        edge_instance.obj_dict['attributes']['fontname']

    """
    def __init__(self, src: EdgeDefinition | Sequence[EdgeDefinition] = ..., dst: EdgeDefinition = ..., obj_dict: AttributeDict | None = ..., **attrs: Any) -> None: ...
    def _get_endpoint(self, position: int) -> EdgeEndpoint: ...
    def get_source(self) -> EdgeEndpoint:
        """Get the edge's source endpoint."""
    def get_destination(self) -> EdgeEndpoint:
        """Get the edge's destination endpoint."""
    def __hash__(self) -> int: ...
    def __eq__(self, edge: object) -> bool:
        """Compare two edges.

        If the parent graph is directed, arcs linking
        node A to B are considered equal and A->B != B->A

        If the parent graph is undirected, any edge
        connecting two nodes is equal to any other
        edge connecting the same nodes, A->B == B->A
        """
    def parse_node_ref(self, node_ref: EdgeEndpoint) -> EdgeEndpoint: ...
    def to_string(self, indent: Any = ..., indent_level: int = ...) -> str:
        """Return string representation of edge in DOT language."""
    def get_edgeURL(self) -> Any: ...
    def set_edgeURL(self, value: Any) -> None: ...
    def get_headtooltip(self) -> Any: ...
    def set_headtooltip(self, value: Any) -> None: ...
    def get_labelfontname(self) -> Any: ...
    def set_labelfontname(self, value: Any) -> None: ...
    def get_arrowsize(self) -> Any: ...
    def set_arrowsize(self, value: Any) -> None: ...
    def get_labelfloat(self) -> Any: ...
    def set_labelfloat(self, value: Any) -> None: ...
    def get_headURL(self) -> Any: ...
    def set_headURL(self, value: Any) -> None: ...
    def get_pos(self) -> Any: ...
    def set_pos(self, value: Any) -> None: ...
    def get_edgetooltip(self) -> Any: ...
    def set_edgetooltip(self, value: Any) -> None: ...
    def get_tailURL(self) -> Any: ...
    def set_tailURL(self, value: Any) -> None: ...
    def get_len(self) -> Any: ...
    def set_len(self, value: Any) -> None: ...
    def get_edgehref(self) -> Any: ...
    def set_edgehref(self, value: Any) -> None: ...
    def get_label(self) -> Any: ...
    def set_label(self, value: Any) -> None: ...
    def get_arrowhead(self) -> Any: ...
    def set_arrowhead(self, value: Any) -> None: ...
    def get_labelfontsize(self) -> Any: ...
    def set_labelfontsize(self, value: Any) -> None: ...
    def get_penwidth(self) -> Any: ...
    def set_penwidth(self, value: Any) -> None: ...
    def get_tailtooltip(self) -> Any: ...
    def set_tailtooltip(self, value: Any) -> None: ...
    def get_href(self) -> Any: ...
    def set_href(self, value: Any) -> None: ...
    def get_id(self) -> Any: ...
    def set_id(self, value: Any) -> None: ...
    def get_minlen(self) -> Any: ...
    def set_minlen(self, value: Any) -> None: ...
    def get_edgetarget(self) -> Any: ...
    def set_edgetarget(self, value: Any) -> None: ...
    def get_tailclip(self) -> Any: ...
    def set_tailclip(self, value: Any) -> None: ...
    def get_tailport(self) -> Any: ...
    def set_tailport(self, value: Any) -> None: ...
    def get_fontsize(self) -> Any: ...
    def set_fontsize(self, value: Any) -> None: ...
    def get_colorscheme(self) -> Any: ...
    def set_colorscheme(self, value: Any) -> None: ...
    def get_layer(self) -> Any: ...
    def set_layer(self, value: Any) -> None: ...
    def get_rank(self) -> Any: ...
    def set_rank(self, value: Any) -> None: ...
    def get_dir(self) -> Any: ...
    def set_dir(self, value: Any) -> None: ...
    def get_weight(self) -> Any: ...
    def set_weight(self, value: Any) -> None: ...
    def get_headport(self) -> Any: ...
    def set_headport(self, value: Any) -> None: ...
    def get_comment(self) -> Any: ...
    def set_comment(self, value: Any) -> None: ...
    def get_color(self) -> Any: ...
    def set_color(self, value: Any) -> None: ...
    def get_tailhref(self) -> Any: ...
    def set_tailhref(self, value: Any) -> None: ...
    def get_target(self) -> Any: ...
    def set_target(self, value: Any) -> None: ...
    def get_lp(self) -> Any: ...
    def set_lp(self, value: Any) -> None: ...
    def get_sametail(self) -> Any: ...
    def set_sametail(self, value: Any) -> None: ...
    def get_headtarget(self) -> Any: ...
    def set_headtarget(self, value: Any) -> None: ...
    def get_labeltooltip(self) -> Any: ...
    def set_labeltooltip(self, value: Any) -> None: ...
    def get_style(self) -> Any: ...
    def set_style(self, value: Any) -> None: ...
    def get_fontname(self) -> Any: ...
    def set_fontname(self, value: Any) -> None: ...
    def get_labelURL(self) -> Any: ...
    def set_labelURL(self, value: Any) -> None: ...
    def get_samehead(self) -> Any: ...
    def set_samehead(self, value: Any) -> None: ...
    def get_taillabel(self) -> Any: ...
    def set_taillabel(self, value: Any) -> None: ...
    def get_lhead(self) -> Any: ...
    def set_lhead(self, value: Any) -> None: ...
    def get_decorate(self) -> Any: ...
    def set_decorate(self, value: Any) -> None: ...
    def get_nojustify(self) -> Any: ...
    def set_nojustify(self, value: Any) -> None: ...
    def get_showboxes(self) -> Any: ...
    def set_showboxes(self, value: Any) -> None: ...
    def get_tooltip(self) -> Any: ...
    def set_tooltip(self, value: Any) -> None: ...
    def get_labelhref(self) -> Any: ...
    def set_labelhref(self, value: Any) -> None: ...
    def get_ltail(self) -> Any: ...
    def set_ltail(self, value: Any) -> None: ...
    def get_labelangle(self) -> Any: ...
    def set_labelangle(self, value: Any) -> None: ...
    def get_headhref(self) -> Any: ...
    def set_headhref(self, value: Any) -> None: ...
    def get_labelfontcolor(self) -> Any: ...
    def set_labelfontcolor(self, value: Any) -> None: ...
    def get_headlabel(self) -> Any: ...
    def set_headlabel(self, value: Any) -> None: ...
    def get_labeltarget(self) -> Any: ...
    def set_labeltarget(self, value: Any) -> None: ...
    def get_URL(self) -> Any: ...
    def set_URL(self, value: Any) -> None: ...
    def get_constraint(self) -> Any: ...
    def set_constraint(self, value: Any) -> None: ...
    def get_fontcolor(self) -> Any: ...
    def set_fontcolor(self, value: Any) -> None: ...
    def get_arrowtail(self) -> Any: ...
    def set_arrowtail(self, value: Any) -> None: ...
    def get_tailtarget(self) -> Any: ...
    def set_tailtarget(self, value: Any) -> None: ...
    def get_headclip(self) -> Any: ...
    def set_headclip(self, value: Any) -> None: ...
    def get_labeldistance(self) -> Any: ...
    def set_labeldistance(self, value: Any) -> None: ...

class Graph(Common):
    """Class representing a graph in Graphviz's dot language.

    This class implements the methods to work on a representation
    of a graph in Graphviz's dot language.

    graph(  graph_name='G', graph_type='digraph',
        strict=False, suppress_disconnected=False, attribute=value, ...)

    graph_name:
        the graph's name
    graph_type:
        can be 'graph' or 'digraph'
    suppress_disconnected:
        defaults to False, which will remove from the
        graph any disconnected nodes.
    simplify:
        if True it will avoid displaying equal edges, i.e.
        only one edge between two nodes. removing the
        duplicated ones.

    All the attributes defined in the Graphviz dot language should
    be supported.

    Attributes can be set through the dynamically generated methods:

     set_[attribute name], i.e. set_size, set_fontname

    or using the instance's attributes:

     Graph.obj_dict['attributes'][attribute name], i.e.

        graph_instance.obj_dict['attributes']['label']
        graph_instance.obj_dict['attributes']['fontname']
    """
    def __init__(self, graph_name: str = ..., obj_dict: AttributeDict | None = ..., graph_type: str = ..., strict: bool = ..., suppress_disconnected: bool = ..., simplify: bool = ..., **attrs: Any) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def get_graph_type(self) -> str | None: ...
    def set_graph_defaults(self, **attrs: Any) -> None: ...
    def get_graph_defaults(self) -> Any: ...
    def set_node_defaults(self, **attrs: Any) -> None:
        """Define default node attributes.

        These attributes only apply to nodes added to the graph after
        calling this method.
        """
    def get_node_defaults(self) -> Any: ...
    def set_edge_defaults(self, **attrs: Any) -> None: ...
    def get_edge_defaults(self) -> Any: ...
    def set_simplify(self, simplify: bool) -> None:
        """Set whether to simplify or not.

        If True it will avoid displaying equal edges, i.e.
        only one edge between two nodes. removing the
        duplicated ones.
        """
    def get_simplify(self) -> bool:
        """Get whether to simplify or not.

        Refer to set_simplify for more information.
        """
    def set_type(self, graph_type: str) -> None:
        """Set the graph's type, 'graph' or 'digraph'."""
    def get_type(self) -> str | None:
        """Get the graph's type, 'graph' or 'digraph'."""
    def set_name(self, graph_name: str) -> None:
        """Set the graph's name."""
    def get_name(self) -> str | None:
        """Get the graph's name."""
    def set_strict(self, val: bool) -> None:
        """Set graph to 'strict' mode.

        This option is only valid for top level graphs.
        """
    def get_strict(self) -> bool:
        """Get graph's 'strict' mode (True, False).

        This option is only valid for top level graphs.
        """
    def set_suppress_disconnected(self, val: bool) -> None:
        """Suppress disconnected nodes in the output graph.

        This option will skip nodes in
        the graph with no incoming or outgoing
        edges. This option works also
        for subgraphs and has effect only in the
        current graph/subgraph.
        """
    def get_suppress_disconnected(self) -> bool:
        """Get if suppress disconnected is set.

        Refer to set_suppress_disconnected for more information.
        """
    def get_next_sequence_number(self) -> int: ...
    def add_node(self, graph_node: Node) -> None:
        """Adds a node object to the graph.

        It takes a node object as its only argument and returns
        None.
        """
    def del_node(self, name: str | Node, index: int | None = ...) -> bool:
        """Delete a node from the graph.

        Given a node's name all node(s) with that same name
        will be deleted if 'index' is not specified or set
        to None.
        If there are several nodes with that same name and
        'index' is given, only the node in that position
        will be deleted.

        'index' should be an integer specifying the position
        of the node to delete. If index is larger than the
        number of nodes with that name, no action is taken.

        If nodes are deleted it returns True. If no action
        is taken it returns False.
        """
    def get_node(self, name: str) -> list[Node]:
        """Retrieve a node from the graph.

        Given a node's name the corresponding Node
        instance will be returned.

        If one or more nodes exist with that name a list of
        Node instances is returned.
        An empty list is returned otherwise.
        """
    def get_nodes(self) -> list[Node]:
        """Get the list of Node instances."""
    def get_node_list(self) -> list[Node]:
        """Get the list of Node instances.

        This method returns the list of Node instances
        composing the graph.
        """
    def add_edge(self, graph_edge: Edge) -> None:
        """Adds an edge object to the graph.

        It takes a edge object as its only argument and returns
        None.
        """
    def del_edge(self, src_or_list: Any, dst: Any = ..., index: int | None = ...) -> bool:
        """Delete an edge from the graph.

        Given an edge's (source, destination) node names all
        matching edges(s) will be deleted if 'index' is not
        specified or set to None.
        If there are several matching edges and 'index' is
        given, only the edge in that position will be deleted.

        'index' should be an integer specifying the position
        of the edge to delete. If index is larger than the
        number of matching edges, no action is taken.

        If edges are deleted it returns True. If no action
        is taken it returns False.
        """
    def get_edge(self, src_or_list: Any, dst: Any = ...) -> list[Edge]:
        """Retrieved an edge from the graph.

        Given an edge's source and destination the corresponding
        Edge instance(s) will be returned.

        If one or more edges exist with that source and destination
        a list of Edge instances is returned.
        An empty list is returned otherwise.
        """
    def get_edges(self) -> list[Edge]: ...
    def get_edge_list(self) -> list[Edge]:
        """Get the list of Edge instances.

        This method returns the list of Edge instances
        composing the graph.
        """
    def add_subgraph(self, sgraph: Subgraph) -> None:
        """Adds an subgraph object to the graph.

        It takes a subgraph object as its only argument and returns
        None.
        """
    def get_subgraph(self, name: str) -> list[Subgraph]:
        """Retrieved a subgraph from the graph.

        Given a subgraph's name the corresponding
        Subgraph instance will be returned.

        If one or more subgraphs exist with the same name, a list of
        Subgraph instances is returned.
        An empty list is returned otherwise.
        """
    def get_subgraphs(self) -> list[Subgraph]: ...
    def get_subgraph_list(self) -> list[Subgraph]:
        """Get the list of Subgraph instances.

        This method returns the list of Subgraph instances
        in the graph.
        """
    def set_parent_graph(self, parent_graph: Common | None) -> None: ...
    def to_string(self, indent: Any = ..., indent_level: int = ..., inline: bool = ...) -> str:
        """Return string representation of graph in DOT language.

        @return: graph and subelements
        @rtype: `str`
        """
    def get_levelsgap(self) -> Any: ...
    def set_levelsgap(self, value: Any) -> None: ...
    def get_label(self) -> Any: ...
    def set_label(self, value: Any) -> None: ...
    def get_mindist(self) -> Any: ...
    def set_mindist(self, value: Any) -> None: ...
    def get_bgcolor(self) -> Any: ...
    def set_bgcolor(self, value: Any) -> None: ...
    def get_clusterrank(self) -> Any: ...
    def set_clusterrank(self, value: Any) -> None: ...
    def get_margin(self) -> Any: ...
    def set_margin(self, value: Any) -> None: ...
    def get_concentrate(self) -> Any: ...
    def set_concentrate(self, value: Any) -> None: ...
    def get_mosek(self) -> Any: ...
    def set_mosek(self, value: Any) -> None: ...
    def get_Damping(self) -> Any: ...
    def set_Damping(self, value: Any) -> None: ...
    def get_landscape(self) -> Any: ...
    def set_landscape(self, value: Any) -> None: ...
    def get_mode(self) -> Any: ...
    def set_mode(self, value: Any) -> None: ...
    def get_overlap(self) -> Any: ...
    def set_overlap(self, value: Any) -> None: ...
    def get_pagedir(self) -> Any: ...
    def set_pagedir(self, value: Any) -> None: ...
    def get_smoothing(self) -> Any: ...
    def set_smoothing(self, value: Any) -> None: ...
    def get_esep(self) -> Any: ...
    def set_esep(self, value: Any) -> None: ...
    def get_sep(self) -> Any: ...
    def set_sep(self, value: Any) -> None: ...
    def get_showboxes(self) -> Any: ...
    def set_showboxes(self, value: Any) -> None: ...
    def get_model(self) -> Any: ...
    def set_model(self, value: Any) -> None: ...
    def get_resolution(self) -> Any: ...
    def set_resolution(self, value: Any) -> None: ...
    def get_layout(self) -> Any: ...
    def set_layout(self, value: Any) -> None: ...
    def get_maxiter(self) -> Any: ...
    def set_maxiter(self, value: Any) -> None: ...
    def get_splines(self) -> Any: ...
    def set_splines(self, value: Any) -> None: ...
    def get_fontcolor(self) -> Any: ...
    def set_fontcolor(self, value: Any) -> None: ...
    def get_dim(self) -> Any: ...
    def set_dim(self, value: Any) -> None: ...
    def get_quantum(self) -> Any: ...
    def set_quantum(self, value: Any) -> None: ...
    def get_nslimit1(self) -> Any: ...
    def set_nslimit1(self, value: Any) -> None: ...
    def get_diredgeconstraints(self) -> Any: ...
    def set_diredgeconstraints(self, value: Any) -> None: ...
    def get_quadtree(self) -> Any: ...
    def set_quadtree(self, value: Any) -> None: ...
    def get_rank(self) -> Any: ...
    def set_rank(self, value: Any) -> None: ...
    def get_dimen(self) -> Any: ...
    def set_dimen(self, value: Any) -> None: ...
    def get_target(self) -> Any: ...
    def set_target(self, value: Any) -> None: ...
    def get_lp(self) -> Any: ...
    def set_lp(self, value: Any) -> None: ...
    def get_fontpath(self) -> Any: ...
    def set_fontpath(self, value: Any) -> None: ...
    def get_dpi(self) -> Any: ...
    def set_dpi(self, value: Any) -> None: ...
    def get_nodesep(self) -> Any: ...
    def set_nodesep(self, value: Any) -> None: ...
    def get_repulsiveforce(self) -> Any: ...
    def set_repulsiveforce(self, value: Any) -> None: ...
    def get_fontnames(self) -> Any: ...
    def set_fontnames(self, value: Any) -> None: ...
    def get_lwidth(self) -> Any: ...
    def set_lwidth(self, value: Any) -> None: ...
    def get_ordering(self) -> Any: ...
    def set_ordering(self, value: Any) -> None: ...
    def get_labeljust(self) -> Any: ...
    def set_labeljust(self, value: Any) -> None: ...
    def get_id(self) -> Any: ...
    def set_id(self, value: Any) -> None: ...
    def get_lheight(self) -> Any: ...
    def set_lheight(self, value: Any) -> None: ...
    def get_compound(self) -> Any: ...
    def set_compound(self, value: Any) -> None: ...
    def get_overlap_scaling(self) -> Any: ...
    def set_overlap_scaling(self, value: Any) -> None: ...
    def get_start(self) -> Any: ...
    def set_start(self, value: Any) -> None: ...
    def get_fontname(self) -> Any: ...
    def set_fontname(self, value: Any) -> None: ...
    def get_mclimit(self) -> Any: ...
    def set_mclimit(self, value: Any) -> None: ...
    def get_truecolor(self) -> Any: ...
    def set_truecolor(self, value: Any) -> None: ...
    def get_nojustify(self) -> Any: ...
    def set_nojustify(self, value: Any) -> None: ...
    def get_K(self) -> Any: ...
    def set_K(self, value: Any) -> None: ...
    def get_pack(self) -> Any: ...
    def set_pack(self, value: Any) -> None: ...
    def get_layersep(self) -> Any: ...
    def set_layersep(self, value: Any) -> None: ...
    def get_sortv(self) -> Any: ...
    def set_sortv(self, value: Any) -> None: ...
    def get_nslimit(self) -> Any: ...
    def set_nslimit(self, value: Any) -> None: ...
    def get_viewport(self) -> Any: ...
    def set_viewport(self, value: Any) -> None: ...
    def get_epsilon(self) -> Any: ...
    def set_epsilon(self, value: Any) -> None: ...
    def get_ranksep(self) -> Any: ...
    def set_ranksep(self, value: Any) -> None: ...
    def get_searchsize(self) -> Any: ...
    def set_searchsize(self, value: Any) -> None: ...
    def get_voro_margin(self) -> Any: ...
    def set_voro_margin(self, value: Any) -> None: ...
    def get_pad(self) -> Any: ...
    def set_pad(self, value: Any) -> None: ...
    def get_size(self) -> Any: ...
    def set_size(self, value: Any) -> None: ...
    def get_fontsize(self) -> Any: ...
    def set_fontsize(self, value: Any) -> None: ...
    def get_colorscheme(self) -> Any: ...
    def set_colorscheme(self, value: Any) -> None: ...
    def get_ratio(self) -> Any: ...
    def set_ratio(self, value: Any) -> None: ...
    def get_comment(self) -> Any: ...
    def set_comment(self, value: Any) -> None: ...
    def get_packmode(self) -> Any: ...
    def set_packmode(self, value: Any) -> None: ...
    def get_remincross(self) -> Any: ...
    def set_remincross(self, value: Any) -> None: ...
    def get_stylesheet(self) -> Any: ...
    def set_stylesheet(self, value: Any) -> None: ...
    def get_rankdir(self) -> Any: ...
    def set_rankdir(self, value: Any) -> None: ...
    def get_levels(self) -> Any: ...
    def set_levels(self, value: Any) -> None: ...
    def get_rotate(self) -> Any: ...
    def set_rotate(self, value: Any) -> None: ...
    def get_orientation(self) -> Any: ...
    def set_orientation(self, value: Any) -> None: ...
    def get_normalize(self) -> Any: ...
    def set_normalize(self, value: Any) -> None: ...
    def get_center(self) -> Any: ...
    def set_center(self, value: Any) -> None: ...
    def get_labelloc(self) -> Any: ...
    def set_labelloc(self, value: Any) -> None: ...
    def get_layers(self) -> Any: ...
    def set_layers(self, value: Any) -> None: ...
    def get_aspect(self) -> Any: ...
    def set_aspect(self, value: Any) -> None: ...
    def get_page(self) -> Any: ...
    def set_page(self, value: Any) -> None: ...
    def get_charset(self) -> Any: ...
    def set_charset(self, value: Any) -> None: ...
    def get_bb(self) -> Any: ...
    def set_bb(self, value: Any) -> None: ...
    def get_URL(self) -> Any: ...
    def set_URL(self, value: Any) -> None: ...
    def get_defaultdist(self) -> Any: ...
    def set_defaultdist(self, value: Any) -> None: ...
    def get_root(self) -> Any: ...
    def set_root(self, value: Any) -> None: ...
    def get_outputorder(self) -> Any: ...
    def set_outputorder(self, value: Any) -> None: ...

class Subgraph(Graph):
    """Class representing a subgraph in Graphviz's dot language.

    This class implements the methods to work on a representation
    of a subgraph in Graphviz's dot language.

    subgraph(graph_name='subG',
             suppress_disconnected=False,
             attribute=value,
             ...)

    graph_name:
        the subgraph's name
    suppress_disconnected:
        defaults to false, which will remove from the
        subgraph any disconnected nodes.
    All the attributes defined in the Graphviz dot language should
    be supported.

    Attributes can be set through the dynamically generated methods:

     set_[attribute name], i.e. set_size, set_fontname

    or using the instance's attributes:

     Subgraph.obj_dict['attributes'][attribute name], i.e.

        subgraph_instance.obj_dict['attributes']['label']
        subgraph_instance.obj_dict['attributes']['fontname']
    """
    def __init__(self, graph_name: str = ..., obj_dict: AttributeDict | None = ..., suppress_disconnected: bool = ..., simplify: bool = ..., **attrs: Any) -> None: ...

class Cluster(Graph):
    """Class representing a cluster in Graphviz's dot language.

    This class implements the methods to work on a representation
    of a cluster in Graphviz's dot language.

    cluster(graph_name='subG',
            suppress_disconnected=False,
            attribute=value,
            ...)

    graph_name:
        the cluster's name
        (the string 'cluster' will be always prepended)
    suppress_disconnected:
        defaults to false, which will remove from the
        cluster any disconnected nodes.
    All the attributes defined in the Graphviz dot language should
    be supported.

    Attributes can be set through the dynamically generated methods:

     set_[attribute name], i.e. set_color, set_fontname

    or using the instance's attributes:

     Cluster.obj_dict['attributes'][attribute name], i.e.

        cluster_instance.obj_dict['attributes']['label']
        cluster_instance.obj_dict['attributes']['fontname']
    """
    def __init__(self, graph_name: str = ..., obj_dict: AttributeDict | None = ..., suppress_disconnected: bool = ..., simplify: bool = ..., **attrs: Any) -> None: ...
    def get_labelloc(self) -> Any: ...
    def set_labelloc(self, value: Any) -> None: ...
    def get_pencolor(self) -> Any: ...
    def set_pencolor(self, value: Any) -> None: ...
    def get_penwidth(self) -> Any: ...
    def set_penwidth(self, value: Any) -> None: ...
    def get_label(self) -> Any: ...
    def set_label(self, value: Any) -> None: ...
    def get_nojustify(self) -> Any: ...
    def set_nojustify(self, value: Any) -> None: ...
    def get_labeljust(self) -> Any: ...
    def set_labeljust(self, value: Any) -> None: ...
    def get_tooltip(self) -> Any: ...
    def set_tooltip(self, value: Any) -> None: ...
    def get_bgcolor(self) -> Any: ...
    def set_bgcolor(self, value: Any) -> None: ...
    def get_K(self) -> Any: ...
    def set_K(self, value: Any) -> None: ...
    def get_fontsize(self) -> Any: ...
    def set_fontsize(self, value: Any) -> None: ...
    def get_colorscheme(self) -> Any: ...
    def set_colorscheme(self, value: Any) -> None: ...
    def get_lheight(self) -> Any: ...
    def set_lheight(self, value: Any) -> None: ...
    def get_color(self) -> Any: ...
    def set_color(self, value: Any) -> None: ...
    def get_sortv(self) -> Any: ...
    def set_sortv(self, value: Any) -> None: ...
    def get_target(self) -> Any: ...
    def set_target(self, value: Any) -> None: ...
    def get_lp(self) -> Any: ...
    def set_lp(self, value: Any) -> None: ...
    def get_lwidth(self) -> Any: ...
    def set_lwidth(self, value: Any) -> None: ...
    def get_URL(self) -> Any: ...
    def set_URL(self, value: Any) -> None: ...
    def get_fillcolor(self) -> Any: ...
    def set_fillcolor(self, value: Any) -> None: ...
    def get_fontcolor(self) -> Any: ...
    def set_fontcolor(self, value: Any) -> None: ...
    def get_style(self) -> Any: ...
    def set_style(self, value: Any) -> None: ...
    def get_peripheries(self) -> Any: ...
    def set_peripheries(self, value: Any) -> None: ...
    def get_fontname(self) -> Any: ...
    def set_fontname(self, value: Any) -> None: ...

class Dot(Graph):
    """A container for handling a dot language file.

    This class implements methods to write and process
    a dot language file. It is a derived class of
    the base class 'Graph'.
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_shape_files(self, file_paths: str | Sequence[str]) -> None:
        """Add the paths of the required image files.

        If the graph needs graphic objects to
        be used as shapes or otherwise
        those need to be in the same folder as
        the graph is going to be rendered
        from. Alternatively the absolute path to
        the files can be specified when
        including the graphics in the graph.

        The files in the location pointed to by
        the path(s) specified as arguments
        to this method will be copied to
        the same temporary location where the
        graph is going to be rendered.
        """
    def set_prog(self, prog: str) -> None:
        """Sets the default program.

        Sets the default program in charge of processing
        the dot file into a graph.
        """
    def write(self, path: str | bytes, prog: str | None = ..., format: str = ..., encoding: str | None = ...) -> bool:
        """Writes a graph to a file.

        Given a filename 'path' it will open/create and truncate
        such file and write on it a representation of the graph
        defined by the dot object in the format specified by
        'format' and using the encoding specified by `encoding` for text.
        The format 'raw' is used to dump the string representation
        of the Dot object, without further processing.
        The output can be processed by any of graphviz tools, defined
        in 'prog', which defaults to 'dot'
        Returns True or False according to the success of the write
        operation.

        There's also the preferred possibility of using:

            write_'format'(path, prog='program')

        which are automatically defined for all the supported formats.
        [write_ps(), write_gif(), write_dia(), ...]

        The encoding is passed to `open` [1].

        [1] https://docs.python.org/3/library/functions.html#open
        """
    def create(self, prog: list[str] | tuple[str] | str | None = ..., format: str = ..., encoding: str | None = ...) -> bytes:
        '''Creates and returns a binary image for the graph.

        create will write the graph to a tempworary dot file in the
        encoding specified by `encoding` and process it with the
        program given by \'prog\' (which defaults to \'twopi\'), reading
        the binary image output and return it as `bytes`.

        There\'s also the preferred possibility of using:

            create_\'format\'(prog=\'program\')

        which are automatically defined for all the supported formats,
        for example:

          - `create_ps()`
          - `create_gif()`
          - `create_dia()`

        If \'prog\' is a list, instead of a string,
        then the fist item is expected to be the program name,
        followed by any optional command-line arguments for it:

            [ \'twopi\', \'-Tdot\', \'-s10\' ]


        @param prog: either:

          - name of GraphViz executable that
            can be found in the `$PATH`, or

          - absolute path to GraphViz executable.

          If you have added GraphViz to the `$PATH` and
          use its executables as installed
          (without renaming any of them)
          then their names are:

            - `\'dot\'`
            - `\'twopi\'`
            - `\'neato\'`
            - `\'circo\'`
            - `\'fdp\'`
            - `\'sfdp\'`

          On Windows, these have the notorious ".exe" extension that,
          only for the above strings, will be added automatically.

          The `$PATH` is inherited from `os.env[\'PATH\']` and
          passed to `subprocess.Popen` using the `env` argument.

          If you haven\'t added GraphViz to your `$PATH` on Windows,
          then you may want to give the absolute path to the
          executable (for example, to `dot.exe`) in `prog`.
        '''
    def create_pic(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_dia(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_dot(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_xdot(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_wbmp(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_pcl(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_vml(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_vmlz(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_cmapx_np(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_jpg(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_imap(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_hpgl(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_vrml(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_mif(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_jpe(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_canon(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_png(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_gd(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_ps(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_vtx(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_ismap(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_xlib(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_imap_np(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_ps2(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_cmapx(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_gd2(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_jpeg(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_cmap(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_fig(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_mp(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_plain(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_svgz(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_gif(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_pdf(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def create_svg(self, prog: list[str] | tuple[str] | str | None = ..., encoding: str | None = ...) -> bytes: ...
    def write_pic(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_dia(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_dot(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_xdot(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_wbmp(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_pcl(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_vmlz(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_vml(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_raw(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_cmapx_np(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_jpg(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_imap(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_hpgl(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_vrml(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_canon(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_mif(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_jpe(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_png(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_gd(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_ps(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_vtx(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_ismap(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_xlib(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_imap_np(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_ps2(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_cmapx(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_gd2(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_jpeg(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_cmap(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_fig(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_mp(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_plain(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_svgz(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_gif(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_pdf(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
    def write_svg(self, path: str | bytes, prog: str | None = ..., encoding: str | None = ...) -> bool: ...
